[versions]
agp = "8.13.2"
coreKtx = "1.18.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"
material = "1.13.0"
activity = "1.13.0"
constraintlayout = "2.2.1"
kotlin = "2.3.20"
ksp = "2.3.6"
ggs = "4.4.4"
crashlytics = "3.0.6"
cameraX = "1.6.0"
cameraXView = "1.6.0"
koinAndroid = "4.2.0"
lifecycleRuntimeKtx = "2.10.0"
multidex = "2.0.1"
shimmer = "0.5.0"
playServicesAds = "24.9.0"
playServicesAdsIdentifier = "18.2.0"
lottie = "6.1.0"
billingKtx = "7.1.1"
guava = "33.2.1-android"
glide = "4.16.0"
glideTransform = "4.3.0"
okhttp = "4.12.0"
dotsIndicator = "4.3"
firebaseBom = "33.15.0"

roundedImageView = "2.3.0"
permissionsDispatcher = "1.1.4"
threetenabp = "1.4.9"
blurview = "version-2.0.6"
converterGson = "2.9.0"
paging3 = "3.3.2"
roomKtx = "2.8.4"
pagingRuntimeKtx = "3.4.1"
gson = "2.13.2"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }

koin-android = { module = "io.insert-koin:koin-android", version.ref = "koinAndroid" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koinAndroid" }
koin-test = { module = "io.insert-koin:koin-test", version.ref = "koinAndroid" }
koin-test-junit4 = { module = "io.insert-koin:koin-test-junit4", version.ref = "koinAndroid" }

androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-multidex = { module = "androidx.multidex:multidex", version.ref = "multidex" }
shimmer = { module = "com.facebook.shimmer:shimmer", version.ref = "shimmer" }
play-services-ads = { module = "com.google.android.gms:play-services-ads", version.ref = "playServicesAds" }
play-services-ads-identifier = { module = "com.google.android.gms:play-services-ads-identifier", version.ref = "playServicesAdsIdentifier" }
lottie = { module = "com.airbnb.android:lottie", version.ref = "lottie" }
billing-ktx = { module = "com.android.billingclient:billing-ktx", version.ref = "billingKtx" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }

okhttp3 = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
okhttp3-logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "converterGson" }
converter-scalars = { module = "com.squareup.retrofit2:converter-scalars", version.ref = "converterGson" }
androidx-paging = { group = "androidx.paging", name = "paging-runtime-ktx", version.ref = "paging3" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "converterGson" }
#Glide
glide = { group = "com.github.bumptech.glide", name = "glide", version.ref = "glide" }
glide-transform = { group = "jp.wasabeef", name = "glide-transformations", version.ref = "glideTransform" }

dots-indicator = { group = "com.tbuonomo", name = "dotsindicator", version.ref = "dotsIndicator" }
rounded-image-view = { group = "com.makeramen", name = "roundedimageview", version.ref = "roundedImageView" }
permissions-dispatcher = { group = "com.github.permissions-dispatcher", name = "ktx", version.ref = "permissionsDispatcher" }

blurview = { module = "com.github.Dimezis:BlurView", version.ref = "blurview" }
threetenabp = { group = "com.jakewharton.threetenabp", name = "threetenabp", version.ref = "threetenabp" }


# CameraX
androidx-camera-core = { group = "androidx.camera", name = "camera-core", version.ref = "cameraX" }
androidx-camera-camera2 = { group = "androidx.camera", name = "camera-camera2", version.ref = "cameraX" }
androidx-camera-lifecycle = { group = "androidx.camera", name = "camera-lifecycle", version.ref = "cameraX" }
androidx-camera-view = { group = "androidx.camera", name = "camera-view", version.ref = "cameraXView" }


#Firebase
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
firebase-messaging = { module = "com.google.firebase:firebase-messaging" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
firebase-config = { module = "com.google.firebase:firebase-config" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics" }
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "roomKtx" }
androidx-room-paging = { group = "androidx.room", name = "room-paging", version.ref = "roomKtx" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomKtx" }

[bundles]
firebase = [
    "firebase-messaging",
    "firebase-analytics",
    "firebase-config",
    "firebase-crashlytics",
]

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
dev-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
jetbrains-kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }
google-services = { id = "com.google.gms.google-services", version.ref = "ggs" }
crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "crashlytics" }
